services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres.yyiwpxirxhfnrprgriib:XV2rqIQjj89nRWUt@aws-0-ap-southeast-1.pooler.supabase.com:6543/postgres
      - TEST_DATABASE_URL=postgresql://postgres.cdmendhimkwadurrvvrm:XB9PO8PxGep8z3Aa@aws-0-ap-southeast-1.pooler.supabase.com:5432/postgres
      - APP_NAME=financial_app
      - AZURE_API_KEY=5fhghJehLo6Gk4HgBDbfUHxkSM1ogJ3X5PGjsk1N40llL1uTfmQRJQQJ99BEACHYHv6XJ3w3AAAAACOG00jb
      - AZURE_API_BASE=https://topex-mbbxsbap-eastus2.openai.azure.com/openai/deployments/gpt-4o-mini/chat/completions?api-version=2025-01-01-preview
