name: Python Test

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh
      - name: Install Dependencies
        working-directory: ./backend
        run: uv sync && uv sync --dev
      - name: Lint
        working-directory: ./backend
        run: uv run ruff check
      - name: Run Tests
        working-directory: ./backend
        run: uv run pytest --cache-clear
